import type { Metadata } from 'next';
import './globals.css';
import { fontArabic, fontEnglishBody, fontEnglishHeading } from '@/lib/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ar' dir='rtl'>
      <body
        className={`
          ${fontArabic.variable}
          ${fontEnglishHeading.variable}
          ${fontEnglishBody.variable}
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
